### ISSUE TITLE
ReferenceError: People is not defined

### ISSUE THREAD

**Issue by systematicallyrandom** [fleapower/Google-Script-Contacts-Sync#1]
Setting up an new sync. I have copied the code to a new Script project, created my spreadsheet, and updated the script with my email addresses and the sheet ID. When I first ran MasterInit it asked for permissions, which I gave it, then I got the following error:
```
11:15:34 AM	Notice	Execution started
11:15:33 AM	Info	<me>@gmail.com
11:15:33 AM	Info	getContactGroupsList
11:15:35 AM	Error	
ReferenceError: People is not defined
getContactGroupsList	@ Code.gs:634
(anonymous)	@ Code.gs:109
```
Subsequent runs give me the same error.

**Comment by systematicallyrandom** [comment]
Interestingly I don't see People as a request scope in the script overview page;

> Project OAuth Scopes
> 5 Scopes Requested
> Allow this application to run when you are not present	https://www.googleapis.com/auth/script.scriptapp
> Send email as you	https://www.googleapis.com/auth/script.send_mail
> See, edit, create, and delete all of your Google Drive files	https://www.googleapis.com/auth/drive
> See, edit, create, and delete all your Google Sheets spreadsheets	https://www.googleapis.com/auth/spreadsheets
> See your primary Google Account email address	https://www.googleapis.com/auth/userinfo.email

Not sure if that is relevant or necessary or not.

**Comment by fleapower** [comment]
Sorry for the trouble.  Did it ask you to add the People API when asking for permissions?  If not, click the plus sign next to "Services" in the script menu bar.  Add the "Peopleapi" to the project.  Please let me know if this fixes it.  Thanks!

**Comment by systematicallyrandom** [comment]
Thanks. I don't recall it prompting for me to add the People API when I gave it permissions, but I may have missed it? I was successfully able to add it manually via the plus sign and that error went away. It asked for permissions again and this time Contact permissions were included.

But now I'm getting this error:
```
11:48:41 AM	Notice	Execution started
11:48:40 AM	Info	innovatable.me@gmail.com
11:48:40 AM	Info	getContactGroupsList
11:48:40 AM	Info	RefreshSynctoken
11:48:42 AM	Error	
Exception: Cannot retrieve the next object: iterator has reached the end.
RefreshSyncToken	@ Code.gs:517
MasterInit	@ Code.gs:113
```
Subsequent runs complain about the tab in the sheet already existing, but if I delete that tab and run it again I get the same error as above.

**Comment by fleapower** [comment]
It looks like it is having a hard time creating/finding the file containing the sync token.  Create an empty text file on your computer and then upload it to your Google drive (really doesn't matter where but for convenience, just put it in the directory with the spreadsheet):

YOUR_EMAIL_ADDRESS@gmail.com_PeopleSyncToken.txt

Replace the placeholder email address with the email address from your master account.  BTW, I don't know if you intended to or not, but your email address was in the previous post.

Delete the tab in the spreadsheet and then try MasterInit again.

**Comment by systematicallyrandom** [comment]
Thank you, I had just noticed my email address in the log outputs! 🤦🏻‍♂️I created and uploaded that file and it ran successfully! 😊

**Comment by fleapower** [comment]
Excellent!  I appreciate you working through this.  You are the first person to encounter these errors (not that there are a ton of people using this).  I will update the instructions to ensure these items are captured.

Let me know how it goes.  The script is pretty robust, so it can recover from most errors or sync issues.  If you get warning/error emails on occasion, don't worry about them - you may get a handful in the first day as the accounts get sync'd or after massive contact changes.  I get about one per week or so, but the script is able to fix itself in the next run.  I've been running fully sync'd for over three months with no hiccups.

Just curious, how many accounts are you synchronizing?

**Comment by systematicallyrandom** [comment]
I'm syncing four accounts total, but I have only started the ClientInit on the first one because I wasn't sure if it was wise to have multiples running at the same time? (~700 contacts.)

It looks like Google is having people manually add the People API in their [example](https://developers.google.com/people/quickstart/apps-script#new-editor_1), so unless there is a way to do that programmatically, you will want to update the instructions to have people do that. 

Also, I'm not an App Script programmer, but I didn't see any code to actually create the token file if it doesn't already exist. I ended up having to manually create the token for all the accounts.

**Comment by fleapower** [comment]
Thanks for the info.  Please let me know how it works with four accounts.  Everyone else I know who is using it only only has it sync'ing two accounts.

I will update the instructions accordingly.

**Comment by acmor** [comment]
[systematicallyrandom](https://github.com/systematicallyrandom) Thanks for creating this report! I got the same error when trying to set up synchronization for three gmail accounts.

[fleapower](https://github.com/fleapower) Thanks for your fast reply and solution. It also seems to work for me now, the contacts arrive in the second and third account :-)

**Comment by systematicallyrandom** [comment]
Sync with four accounts seems to work fine. You just don't want to make any changes or deletes to any of your contacts until everything has fully synced, which seemed to take longer than when all the contacts appeared in all the accounts. Otherwise they get overwritten. But once everything is humming along it seems to work as expected!

**Comment by fleapower** [comment]
Thanks for the update!
