### ISSUE TITLE
Update the instructions: don't "share" the script between accounts

### ISSUE THREAD

**Issue by knwpsk** [fleapower/Google-Script-Contacts-Sync#11]
I "think" sharing the script between users creates a problem. I think when you do this, it also "shares" the associated triggers... and this can cause some weird behavior. 
When I started with just two accounts, it all seemed ok.
But when I added the third account, things got out of hand, and my accounts seemed to be "updating" each other in circles. I'm not certain, but I think when one user/account creates a Trigger for the script, that it causes the other users/accounts to activate on that same trigger. 
I think it's safer if each user runs their own copy of the script, with their own, separate triggers. 
Am I wrong?

**Comment by fleapower** [comment]
I've never had it share the triggers.  I'll take a look.

**Comment by knwpsk** [comment]
I'll test this and confirm it. I'm not certain about it. "Something" odd happened... but I'm not sure that this was it.

**Comment by fleapower** [comment]
When there are multiple accounts and lots of contacts, it can appear contacts are being cyclically sync'd, but it eventually smooths out.
