### ISSUE TITLE
Setup and execution done, silly newbie follow-up questions

### ISSUE THREAD

**Issue by glimpsiz** [fleapower/Google-Script-Contacts-Sync#13]
Firstly, thank you for doing this! Really appreciate it and super excited to get this working. Setup and ran the steps as instructed for 1 master and 1 client account. There are ~4,000 contacts in the master account. Here are some questions: 

1. How long should it take for contacts to show up in the client account? It's been ~an hour since the scripts executed successfully.
2. I see the Google Sheet now has 29 columns and 35 rows, some have specific values and some are generic. Should I be concerned? Should it have ALL ~4000 contact entries? The other 2 tabs are completely empty - no column names either.
3. In the future, once the contacts have synced - Do I have to run the script manually to sync contacts between accounts? If so, could it be set to run nightly?
4. If not already, can I sync 'Other Contacts'? ie ones that are not part of My Contacts? 
Thank You!

**Comment by glimpsiz** [comment]
Update: 
1. approximately 24 hours in, about half (~1700) of the Contacts are now in the Client account. 
2. Got ~400 emails notifying conflicts 
3. Labels for contacts in client account are not updated yet, I suppose that will happen once all contacts are synced

**Comment by glimpsiz** [comment]
3 days in, most of my contacts in the client account are mixed up - name of a contact with email and phone numbers of another. Suggestions to merge contacts with different names and phone numbers. Still getting a few dozen emails a day notifying of conflict. Primary account seems to be okay. Will let it continue for another day or so before deciding to nix and restore backup. Would love to hear if anyone else had a similar experience or have recommendations.

**Comment by glimpsiz** [comment]
Day 4 update - 
1. Main account has ~2x contacts, half of them flagged as duplicates  
2. Client account has 'stabilized' on number of contacts, though data is still messed up. 
3. Conflict emails continuing to come in, ~150-200/day

**Comment by fleapower** [comment]
It shouldn't have taken so long to sync.  It is about 1,000 contacts per hour.

Did you modify the sheet in _any_ way?  Even just changing a single cell can cause the issues you are seeing.  The script is fairly robust in correcting errors unless you mess with the spreadsheet.  Not all changes Google tracks are readily apparent to the end user so the script may _see_ the spreadsheet differently than you do.

**Comment by glimpsiz** [comment]
> It shouldn't have taken so long to sync. It is about 1,000 contacts per hour.
> 
> Did you modify the sheet in _any_ way? Even just changing a single cell can cause the issues you are seeing. The script is fairly robust in correcting errors unless you mess with the spreadsheet. Not all changes Google tracks are readily apparent to the end user so the script may _see_ the spreadsheet differently than you do.

No changes were made though it looks like something was not right so I am about restore backup and give it another try. Contacts in the primary account are also now 'infected' :)  Will update on attempt 2 soon

**Comment by glimpsiz** [comment]
Update - Deleted all contacts from Client and Primary, deleted Google Sheet, deleted and recreated txt files for respective accounts. Restored backup CSV to Primary account. Started the script again ~12 hours ago. So far, ~2000 contacts on client account have synced - ~50 duplicates identified by Google Contacts in client account (compared to 0 in the primary). The data in those contacts is incorrect (perhaps from the script?) - saw some comments that it should eventually get fixed so I'll let it run for the rest of the day and check-in again.

**Comment by glimpsiz** [comment]
Update - Back to square one. Client account has ~2900 duplicate contacts. In most cases that I manually reviewed, there just seem to be two of the same. Not sure why because the primary only has a unique contact for all. 
In some cases, ~10% that I sampled, the email for one contact has been inserted in to the email field for another contact - which then makes Google Contacts trigger it as a duplicate. I am intrigued why this happening, it seems pretty random. Someone international with a name starting with A has an email for someone local here with a name starting with S. Name email and phone are the only details for these (and other infected) contacts, and some have one not the other.  
Very intrigued why this isn't working for me when it is for others. What am I doing different, unintentionally?

**Comment by fleapower** [comment]
Without actually knowing exactly what you are doing, it is difficult to know what might be going wrong.  I haven't seen this extensive of a problem before.  Not to be patronizing, but have you read through all of the documentation and instructions to ensure you aren't missing something?

**Comment by knwpsk** [comment]
Again not at all to be patronizing, but just to encourage you Glimpsiz: I followed the instructions and installed without much trouble. It does work. 
Maybe try starting fresh and see if you missed a step somewhere?

**Comment by glimpsiz** [comment]
@knwpsk @fleapower you're not patronizing at all. I am amused(?) myself why this isn't working. I plan to do a screen capture as I try this one final time. Curious: Would either of you be open to a 15-min screen share as I set this up instead of me posting potentially sensitive data in public through the screen share? I know you can blur etc but there's always something that can be missed out.

**Comment by knwpsk** [comment]
@glimpsiz I'd say yes to that if I had any confidence that I could help, but I don't. I only did the setup "once", a long time ago, and don't have enough memory or familiarity with it to think that I could spot anything.

**Comment by fleapower** [comment]
@glimpsiz Did you get this working?  I've been out of town most of March so haven't had a time to circle back.
