### ISSUE TITLE
Quota Exceeded error on running ClientInit

### ISSUE THREAD

**Issue by noamross** [fleapower/Google-Script-Contacts-Sync#16]
Hi, thanks for the great script!

I'm experiencing an error on setup. After successfully executing the `MasterInit` function on my master account, I'm running ClientInit on my one client account.  I get the following error after running it:

```
GoogleJsonResponseException: API call to people.people.updateContact failed with error: Quota exceeded for quota metric 'Critical read requests (Contact and Profile Reads)' and limit 'Critical read requests (Contact and Profile Reads) per minute per user' of service 'people.googleapis.com' for consumer 'project_number:453227609897'.
SpreadsheetToContacts @ Code.gs:428 
ClientInit @ Code.gs: 
```

About 140 of 1600 contacts had been sync'd from master to client account when I got this error.  I re-ran ClientInit and got the error once again after a number of contacts were updated, and I still had 140 in the client account. 

Is this expected? Will the triggers now set eventually repeat tasks enough to finish syncing?

**Comment by noamross** [comment]
I note that the time-driven triggers for ClientInit seem to be executing, and failing with the same error. The number of contacts in the client account is not increasing, as it seems to be updating the same contacts and then failing, rather than syncing new contacts.

**Comment by noamross** [comment]
OK, now that they have been running for a while, occasionally the ClientInit runs go long enough to add a few more records (now it is up to 200 of 1600 contacts, 3 hours later).  

I tested extending the sleep timer at https://github.com/fleapower/Google-Script-Contacts-Sync/blob/main/GSCS.js#L426 from 700 to 2000 to prevent timeouts.  This prevents the failure but every run still is updating the same first batch of contacts, so the number of contacts sync'd to the client account remains about 200.

**Comment by fleapower** [comment]
Did you try extending the sleep timer?  Did it work?  The reason it is there is because of quota timeouts with Google scripts.

**Comment by noamross** [comment]
I'm not sure why, but a fresh install of everything solved this problem.  Extending the sleep timer didn't help, something else was happening that kept the updates from being incremental rather than starting from the top.
