### ISSUE TITLE
Data in Google Sheets look like JSON data

### ISSUE THREAD

**Issue by igavronski** [fleapower/Google-Script-Contacts-Sync#3]
Hi there,
I am following your instructions with the script. When I run the step 17, I get:
![Screenshot 2022-06-27 114047](https://user-images.githubusercontent.com/14096908/175968542-0e60a919-56af-4492-a448-df09474f42c5.jpg)
I wanted to have a human readable (and updatable) data on these sheets. Is this the expected behaviour?
Thanks in advance!
Iuri.

**Comment by igavronski** [comment]
Hi,
I just wanted a two-way sync between my Google Contacts and one sheet, in human readable format. Is there any way I could get that done with your script?
Thanks.

**Comment by fleapower** [comment]
Yes, but it would require quite a bit of code rewrite.  Your better bet would be to use IFTTT or Zapier.  What is your end goal?  What are you trying to accomplish?  I might be able to help you come up with some simpler solutions.

**Comment by igavronski** [comment]
Hi,
I want to have my clients list on a sheet, so I can filter calls and texts I needed to do that day, and my clients' info would be sent back to my contacts list.

**Comment by fleapower** [comment]
I see.  What field do you want to use to filter?

**Comment by igavronski** [comment]
In fact, the filtering part is not the most important. I can do that in Sheets with Google's own UI. The back and forth syncing it is.

**Comment by fleapower** [comment]
Hmm...OK.  What field are you going to be updating in the spreadsheet that you need sync'd?

**Comment by igavronski** [comment]
Let me try to explain:
* I have a bunch of contacts (~400) on my Contacts.
*  I have ~400 leads in an Excel sheet
* I want to get my contacts in a Google Sheets
* Then paste my leads into the Google Sheets 
* Clean up the duplicates and have information on them saved (e.g. date of last call and a short memo field)
* Merge it back to Google Contacts
* From then on, sync both sources (Contacts and Sheets) with new info. For example, names or spouse.

**Comment by igavronski** [comment]
I use Google's labels to classify my contacts.

**Comment by fleapower** [comment]
Hmm...maybe just try Zapier or IFTTT.  I know they do have free plans.

**Comment by igavronski** [comment]
Thanks!
