### ISSUE TITLE
Newbie having trouble

### ISSUE THREAD

**Issue by doughertykeegan1** [fleapower/Google-Script-Contacts-Sync#5]
Hi there, 
I've tried this on both my Google Workspace and personal account and get the same error when I run the script

Exception: Cannot retrieve the next object: iterator has reached the end.
RefreshSyncToken	@ Code.gs:528
ClientInit	@ Code.gs:205

Any clue what I'm doing wrong? I have gone through it a few times and can't find any skipped steps. 
Thanks in advance, this will be a godsend once it's running!

**Comment by fleapower** [comment]
Did you ever get this working?

**Comment by noamross** [comment]
I had this issue and solved it by sharing the file `client.account@some.domain_PeopleSyncToken.txt`, stored in the mater account drive, with the client.account@some.domain account.

**Comment by knwpsk** [comment]
@noamross I don't think that was your problem. There should be a different sync token file in _each_ of your accounts, and it doesn't need to be shared with the other accounts. 
In fact, if one account somehow accesses the other account's token file, it would mess up your sync. 

Tangent: here's a quick warning, too: DON'T pen the sync token file using the Google Drive editor. Google Drive will create a new Google Docs version of the file... and this will also mess up your sync. If you need to examine that file for any reason, download it first, and open it locally using Notepad or whatever text editor you use.
