### ISSUE TITLE
Bug with sync token file in Gsuite account

### ISSUE THREAD

**Issue by knwpsk** [fleapower/Google-Script-Contacts-Sync#8]
In the process of adding another account to sync, I found a weird behavior in Google Workspace (Gsuite) > Drive.
When I create the youraccount@domain.com_PeopleSyncToken.txt file on my desktop and drag it into Drive in my Gsuite account, google drops the ".txt" suffix. In gdrive, the file is simply called  "youraccount@domain.com_PeopleSyncToken". The clientInit > RefreshSyncToken() function chokes, saying that people.connections is using a bad parameter. 

Debugging this, I found that the sync token value that the script was getting back from refreshSyncToken was a bunch of garbage, which seems to indicate that Gdrive is reading the file through a pdf decoder. 

To solve this, for now, I had to create the sync token file, and save in on my PC to a folder that gets synchronized to Gdrive using the google drive desktop app. Now when the file appears in gdrive, it has the '.txt' suffix. And now when the script reads that file, it gets (nothing) or (the proper token string) as intended (without trying to read the file as a pdf).

Unsure if there's a more robust way for the script to save sync token in a file?
One thing I think "could" be done is to save the sync token to a script/User property instead of a file. I'll be happy to help with that if desirable.

**Comment by fleapower** [comment]
You have to be sure that the option for Google to convert files is not turned on.  Otherwise, it will convert txt files into Google doc files on upload.

**Comment by knwpsk** [comment]
Apologies, I missed that in the instructions. Thanks.
