### ISSUE TITLE
Enhancement: don't sync "starred" property (or make it optional)

### ISSUE THREAD

**Issue by knwpsk** [fleapower/Google-Script-Contacts-Sync#9]
Maybe in two different accounts, the user(s) don't want the same Contacts to be "starred".
Maybe the "starred" property should not be synced; or it could be configurable in the script.

**Comment by fleapower** [comment]
Easy enough to modify the script to not sync the stars.  Feel free to do so!

**Comment by knwpsk** [comment]
Flea can you say just a bit more about how/where to do this?

**Comment by fleapower** [comment]
As far as I know, the stars are just labels/groups, so it would be same as what I posted in the other thread.
